package GUI;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;

public class PelangganScreenMenu extends javax.swing.JFrame {
    private Map<String, ArrayList<String>> ruteToSopirMap;
    private String username;
    public PelangganScreenMenu(PelangganLoginMenu namaUser){
        setTitle("Pemesanan");
        initComponents();
        this.username = namaUser.getUsername();
        setLocationRelativeTo(null);
        ruteToSopirMap = new HashMap<>();
        readSopirData();
        updateSopirComboBox();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pelangganPilihRute = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        PesananButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TanggalSewa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LamaSewa = new javax.swing.JTextField();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pemesanan");

        jLabel2.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 24)); // NOI18N
        jLabel2.setText("Filkom Tour & Travel");

        jLabel7.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        jLabel7.setText("Pilih Sopir");

        jButton2.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelangganLoginMenu(evt);
            }
        });

        PesananButton.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N
        PesananButton.setText("Pesanan Anda");

        PesananButton.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                pesananButtonActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N
        SubmitButton.setText("Submit");

        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        jLabel8.setText("Pilih Rute");
        pelangganPilihRute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-","SURABAYA-MALANG", "MADURA-MALANG", "BANYUWANGI-MALANG", "SITUBONDO-MALANG", "TULUNGAGUNG-MALANG" }));
        pelangganPilihRute.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 13));
        pelangganPilihRute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganPilihRuteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        jLabel9.setText("Lama Sewa");

        TanggalSewa.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N
        TanggalSewa.setText("DD/MM/YYYY");
        TanggalSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalSewaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        jLabel10.setText("Hari");

        jLabel11.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        jLabel11.setText("Tanggal Penyewaan");

        LamaSewa.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PesananButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubmitButton)
                                .addGap(8, 8, 8))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(LamaSewa, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel10)
                                                                .addGap(42, 42, 42))
                                                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(TanggalSewa))
                                                .addGap(30, 30, 30))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pelangganPilihRute, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, Short.MAX_VALUE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(pelangganPilihRute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(LamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(TanggalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(PesananButton)
                                        .addComponent(SubmitButton))
                                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void pesananButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setUsername(username);
        PesananPelanggan list = new PesananPelanggan(this);
        list.setVisible(true);
        this.dispose();
    }
    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsername() {
        return username;
    }
    private void SubmitButtonPerformed(java.awt.event.ActionEvent evt){
        savePemesananData();
        pelangganPilihRute.setSelectedIndex(0);
        LamaSewa.setText("");
        TanggalSewa.setText("DD/MM/YYYY");
        PelangganScreenMenu screenMenu = new PelangganScreenMenu(new PelangganLoginMenu(username));
        screenMenu.setVisible(true);
        this.dispose();
    }
    private void PelangganLoginMenu(java.awt.event.ActionEvent evt) {
        PelangganLoginMenu plgLgMenu = new PelangganLoginMenu();
        plgLgMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PelangganLoginMenu

    private void TanggalSewaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalSewaActionPerformed
    private void readSopirData() {
        try (BufferedReader reader = new BufferedReader(new FileReader("Sopir.txt"))) {
            String line;
            String nama = null;
            String rute = null;
            String status = null; // Add status variable
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("Nama          :")) {
                    nama = line.split(":")[1].trim();
                } else if (line.startsWith("Rute          :")) {
                    rute = line.split(":")[1].trim();
                } else if (line.startsWith("Status        :")) {
                    status = line.split(":")[1].trim();
                } else if (nama != null && rute != null && status != null && status.equals("Available")) {
                    ruteToSopirMap.computeIfAbsent(rute, k -> new ArrayList<>()).add(nama);
                    nama = null;
                    rute = null;
                    status = null;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal membaca data sopir.");
        }
    }
    private void pelangganPilihRuteActionPerformed(java.awt.event.ActionEvent evt) {
        updateSopirComboBox();
    }
    private void updateSopirComboBox() {
        jComboBox3.setFont(new java.awt.Font("ITF Devanagari Marathi", 1, 13));
        String selectedRute = (String) pelangganPilihRute.getSelectedItem();
        ArrayList<String> sopirList = ruteToSopirMap.getOrDefault(selectedRute, new ArrayList<>());
        jComboBox3.removeAllItems();
        for (String sopir : sopirList) {
            jComboBox3.addItem(sopir);
        }
    }
    private void updateDriverStatus(String driverName) {
        try (BufferedReader reader = new BufferedReader(new FileReader("Sopir.txt"))) {
            StringBuilder fileContent = new StringBuilder();
            String line;
            boolean isDriverFound = false;
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("Nama          :") && line.contains(driverName)) {
                    isDriverFound = true;
                }

                if (isDriverFound && line.startsWith("Status") && line.contains("Available")) {
                    line = line.replace("Available", "Unavailable");
                    isDriverFound = false;
                }
                fileContent.append(line).append("\n");
            }

            // Write the updated content back to the file
            try (FileWriter writer = new FileWriter("Sopir.txt", false)) {
                writer.write(fileContent.toString());
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memperbarui status sopir.");
        }
    }
    private void savePemesananData() {
        String nama = jComboBox3.getSelectedItem().toString();
        String lamaSewa = LamaSewa.getText();
        String tanggalPenyewaan = TanggalSewa.getText();
        updateDriverStatus(nama);
        try (FileWriter writer = new FileWriter(username + ".txt", true)) {
            writer.write("Username         : " + username + "\n"); // Simpan username
            writer.write("Nama Sopir       : " + nama + "\n");
            writer.write("Lama Sewa        : " + lamaSewa + " hari\n");
            writer.write("Tanggal Penyewaan: " + tanggalPenyewaan + "\n\n");

            JOptionPane.showMessageDialog(this, "Data pemesanan berhasil disimpan.");

        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data pemesanan.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        PelangganLoginMenu loginMenu = new PelangganLoginMenu();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                loginMenu.setVisible(true);
            }
        });
        PelangganScreenMenu screenMenu = new PelangganScreenMenu(loginMenu);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                screenMenu.setVisible(true);
            }
        });
    }

    private javax.swing.JButton PesananButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> pelangganPilihRute;
    private javax.swing.JTextField TanggalSewa;
    private javax.swing.JTextField LamaSewa;

}
